CBDEMO-123

diff --git a/.cloudbees/workflows/buildanddeploy.yaml b/.cloudbees/workflows/buildanddeploy.yaml
--- a/.cloudbees/workflows/buildanddeploy.yaml
+++ b/.cloudbees/workflows/buildanddeploy.yaml
@@ -11,6 +11,7 @@ jobs:
       unitTestResults: ${{ steps.RunUnitTest.outputs.mvn_test_stdio1 }}
       commit_id: ${{ steps.commitinfo.outputs.commit_id }}
       commit_msg: ${{ steps.commitinfo.outputs.commit_msg }}
+      jira_key: ${{ steps.commitinfo.outputs.jira_key }}
     steps:
       - name: Configure git
         uses: docker://alpine/git:latest
@@ -25,8 +26,15 @@ jobs:
           COMMIT_ID=$(git rev-parse HEAD)
           COMMIT_MSG=$(git log -1 --pretty=%B)
 
+          JIRA_KEY=$(echo "$COMMIT_MSG" | grep -oE "[A-Z]+-[0-9]+")
+          if [ -z "$JIRA_KEY" ]; then
+            echo "Error: Commit message must include a valid JIRA issue key." >&2
+            exit 1
+          fi
+
           echo "commit_id=${COMMIT_ID}" >> $CLOUDBEES_OUTPUTS/commit_id
           echo "commit_msg=${COMMIT_MSG}" >> $CLOUDBEES_OUTPUTS/commit_msg
+          echo "jira_key=${JIRA_KEY}" >> $CLOUDBEES_OUTPUTS/jira_key
       - uses: docker://maven:3-eclipse-temurin-17
         name: Build
         kind: build
